frontend:
  image:
    repository: ghcr.io/nicocalvelo/pixel-war-frontend
    tag: d2fb096bbaec16043b538722b05d2a1512ce3615
  replicas: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: ghcr.io/nicocalvelo/pixel-war-backend
    tag: d2fb096bbaec16043b538722b05d2a1512ce3615
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 3001

db:
  image:
    repository: postgres
    tag: "15-alpine"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage: 1Gi
  service:
    port: 5432

database:
  name: pixelwar
  user: pixelwar
  password: pixelwar
