apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pixel-war.fullname" . }}-db
  labels:
    {{- include "pixel-war.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "pixel-war.fullname" . }}-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "pixel-war.fullname" . }}-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: {{ .Values.db.service.port }}
          envFrom:
            - secretRef:
                name: {{ include "pixel-war.fullname" . }}-db-secret
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.database.user }}"]
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.database.user }}"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: {{ include "pixel-war.fullname" . }}-db-pvc
