apiVersion: v1
kind: Service
metadata:
  name: {{ include "pixel-war.fullname" . }}-backend
  labels:
    {{- include "pixel-war.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "pixel-war.fullname" . }}-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
