apiVersion: v1
kind: Service
metadata:
  name: {{ include "pixel-war.fullname" . }}-frontend
  labels:
    {{- include "pixel-war.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ include "pixel-war.fullname" . }}-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      nodePort: 30080
