apiVersion: v1
kind: Service
metadata:
  name: {{ include "pixel-war.fullname" . }}-db
  labels:
    {{- include "pixel-war.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "pixel-war.fullname" . }}-db
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
